server.port=8081
server.address=0.0.0.0
spring.datasource.url=jdbc:mysql://localhost:3306/nsv_schema
spring.datasource.username=root
spring.datasource.password=MyNewPassword123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# OAuth2 Resource Server JWT config
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-csgurp4hmblyo844.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://dev-csgurp4hmblyo844.us.auth0.com/.well-known/jwks.json
