# application-dev.properties # -Dspring.profiles.active=prod
server.port=80
spring.application.name=supplychainManagement-main

# application.properties (default)
spring.profiles.active=dev

# Load additional module-specific configs
spring.config.import=optional:classpath:auth-service.properties,optional:classpath:product-service.properties
