server.port=8084
server.address=0.0.0.0
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:33796/nsv_schema
#spring.datasource.username=root
#spring.datasource.password=kKTtYoOLNAnOJHlrOvkiRLJIqMDePEax
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Auth0 JWT validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_URI}

#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-csgurp4hmblyo844.us.auth0.com/
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://dev-csgurp4hmblyo844.us.auth0.com/.well-known/jwks.json
